# Generated by Django 5.1.3 on 2024-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('trainee_number', models.CharField(max_length=100, unique=True)),
                ('course', models.CharField(max_length=255)),
                ('nin', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self-employed', 'Self-Employed'), ('student', 'student')], max_length=25)),
                ('overall_rating', models.CharField(max_length=10)),
                ('instructor_rating', models.CharField(max_length=10)),
                ('skills_gained', models.TextField()),
                ('skills_application', models.TextField()),
                ('suggestions', models.TextField()),
                ('image', models.ImageField(upload_to='feedback_images/')),
            ],
        ),
    ]
