# Generated by Django 5.1.3 on 2024-11-19 18:16

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='feedback_images/', validators=[feedback.models.FeedBack.validate_image_size]),
        ),
    ]
