# Generated by Django 5.1.3 on 2024-11-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self-employed', 'Self-Employed'), ('student', 'Student')], max_length=25),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
