# Generated by Django 5.1.3 on 2024-11-20 12:31

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self-employed', 'Self-Employed'), ('student', 'student')], max_length=25),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/', validators=[feedback.models.FeedBack.validate_image_size]),
        ),
    ]
