# Generated by Django 5.1.3 on 2024-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
