# Generated by Django 5.1.3 on 2024-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_remove_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
