# Generated by Django 5.1.3 on 2025-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='employment_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='instructor_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='skills_application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='skills_gained',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
